### ISSUE TITLE
build problem /usr/bin/ld: /usr/local/lib/libavformat.a(aviobuf.o): relocation R_X86_64_32 against `ffurl_context_class' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by arpu** [Xingtao/FFdynamic#1]
using latest master and ffmpeg 4.1 i get this on ubuntu Ubuntu Xenial (16.04 LTS) 

ffmpeg is build with default values

**Comment by arpu** [comment]
i need recompile ffmpeg with -fPIC ?  
any hint is welcome

**Comment by Xingtao** [comment]
Rebuild FFmpeg with '--enable-shared'  option should fix it

**Comment by Xingtao** [comment]
If compiling issue remains, you can refer to 'FFdynamic/tools/dockerlize/ial_docker/ial_dockerfile', this  docker file contains scripts to build dependencies.
