### ISSUE TITLE
Problem with protobuf when trying to test the ial app in a docker container (AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key')

### ISSUE THREAD

**Issue by AlxndrPsclt** [Xingtao/FFdynamic#11]
I'm trying to use the ial app in the docker container. The ialService server compiles and starts fine.

But when I try to test it with the included script, it fails with this stamge AttributeError.
I'm running the test still from the container, after having installed requests and protobuf via pip3.
(protobuf-3.11.3)

```
root@e6178dcc46a3:/tmp/workdir/FFdynamic/apps/interactiveLive/testScripts# python3 testIal.py

Traceback (most recent call last):
  File "testIal.py", line 10, in <module>
    import davStreamletSetting_pb2 as streamlet
  File "../build/protos/davStreamletSetting_pb2.py", line 14, in <module>
    import davWaveSetting_pb2 as davWaveSetting__pb2
  File "../build/protos/davWaveSetting_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

Any idea about how to fix this? Is it a problem with the version of protobuf I use?

**Comment by Xingtao** [comment]
It is probally a version mismatch of protobuf: pip3 install 3.11.3, but in docker file it pulls the latest protobuf, compile and link it (c++ libraries).

Try change the dockerfile with clone version 3.11 may solve the issue.
