### ISSUE TITLE
Mixing streams without sound

### ISSUE THREAD

**Issue by EvK** [Xingtao/FFdynamic#13]
I'm trying to mix some streams which might or might not have sound (not just silence, but absence of audio stream, only video one). I was able to mix when no streams have audio, by removing "audio_encode" entry under "output_settings" in configuiration. However, if one stream has audio and the other does not - I'm having troubles with mixing and almost every frame outputs this:

` audioSyncer.cpp:76] AudioSyncer139808768794112Audio data is in future, cur 14700, desired 14700. video peer 29400, video mix 14700, audio mix 0`

`audioMix.cpp:206] [AudioMix-auto4] {code:-22, detail: Invalid argument, cannot allocate mixed frame data, discard one mixed frame}`

My audio encode option for this case is:

```
"audio_encode" : {
        "encode_type" : "ffmpeg",
        "codec_name" : "aac",
        "avdict_encode_option" : {"ac" : "2", "ab" : "128k", "ar" : "44100"}
      }
```

Any clues?

**Comment by Xingtao** [comment]
Hi, I am not sure what is going on.

But there is an explicit  video connection only call, try change: 

https://github.com/Xingtao/FFdynamic/blob/86fbdfc71bbb6a7665e3fc985a4add20904f1c04/apps/interactiveLive/ialService.cpp#L111
···
inputStreamlet >> mixStreamlet; 
to
inputStreamlet >= mixStreamlet;
···
when no audio stream in inputStreamlet
