### ISSUE TITLE
Layout and Cells clarification

### ISSUE THREAD

**Issue by jagadishkamathk** [Xingtao/FFdynamic#24]
I'm trying to use FFDynamic for more of switching application between multiple inputs. My layout is always eSingle_1. I'm trying to figure out which of the input must be chosen for display amongst may inputs. It looks like its always the first input gets displayed. I tried with options such as ""cells" : [{"layer": -1}, {"layer":1}]" but nothing seem to change the input that is being displayed. Any help is appreciated here

Another issue that I found is with video resolution. Even though I set "avdict_encode_option":  {"width" : "256", "height" : "144"}, it doesnt seem to be taking this width and height and displaying based on input resolution

**Comment by Xingtao** [comment]
Layer is not supported right now.
Try use {"video_size" : "256x144"} in config file, that should change the resolution.

I am working on an anhanced version  of the app, that would have layer support and other features.

**Comment by jagadishkamathk** [comment]
Thank you very much. Any approximate ETA on that feature? Glad to contribute in any way
