### ISSUE TITLE
RTMP lose connect

### ISSUE THREAD

**Issue by Hehaooguoo** [Xingtao/FFdynamic#26]
i use ialservice，to push rtmp to a rtmp server。when i close one input url （rtmp），ial_server  in a error 

E0511 08:26:39.597858 71915 davProc.cpp:174] [Mux-ffmpeg3] {code:-32, detail: Broken pipe, Fail with proc one frame; try again}

i think rtmp connect is broken, then i try to reconnect by onDynamicallyInitializeViaTravelStatic . it works ,but when i add a new input url by pytest, a new trouble comes out 

"AudioSyncer140734468460848Audio data is in future, cur 802202, desired 799262. video peer 1268610, video mix 1337700, audio mix 868352"

**Comment by Xingtao** [comment]
Hi,
"AudioSyncer140734468460848Audio data is in future, cur 802202, desired 799262"   does this one cause A-V not sync ?

**Comment by Hehaooguoo** [comment]
i think i fixed it, in audioMix.cpp 156 line , //m_syncers.erase(from) , now it seem ok.
