### ISSUE TITLE
Error while linking cxx executable ialservice

### ISSUE THREAD

**Issue by Creepios** [Xingtao/FFdynamic#7]
Hello,
I'm on Raspbian 10
I have the following problem:
when I execute the build.sh in the interactive live folder, then it gives a error here:

[ 65%] Linking CXX executable ialService
/usr/bin/ld: FFdynamic/libffdynamic.so: undefined reference to `lzma_stream_decoder'
/usr/bin/ld: FFdynamic/libffdynamic.so: undefined reference to `lzma_code'
/usr/bin/ld: FFdynamic/libffdynamic.so: undefined reference to `lzma_end'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ialService.dir/build.make:124: ialService] Error 1
make[1]: *** [CMakeFiles/Makefile2:74: CMakeFiles/ialService.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

How to fix it?

**Comment by Xingtao** [comment]
hi, have a try
`apt-get install liblzma-dev`

**Comment by Creepios** [comment]
hi, unfortunately it didn't help. :(
It was already installed.

**Comment by Xingtao** [comment]
I am not sure, perhaps explicitly link this library? Try add
``` lzma ``` 
in apps/interactiveLive/CMakeLists.txt 's last line.

**Comment by Creepios** [comment]
Sorry but I don't have any experience to add these things :D The following error:
`CMake Error at CMakeLists.txt:94:
  Parse error.  Expected "(", got newline with text "

  ".`

**Comment by Xingtao** [comment]
Hi, try add 'lzma' to the last line like this:
```
target_link_libraries(ialService
  | PUBLIC ffdynamic::ffdynamic httputil::httputil pbtree::pbtree ffdynaProto::ffdynaProto protobuf::libprotobuf
  | PUBLIC lzma boost_system Threads::Threads)
```

**Comment by Creepios** [comment]
Now there is the following Error:

[ 66%] Building CXX object FFdynamic/davTests/CMakeFiles/avMixerTest.dir/avMixTest.cpp.o
[ 68%] Building CXX object FFdynamic/davTests/CMakeFiles/avMixerTest.dir/testCommon.cpp.o
[ 69%] Linking CXX executable avMixerTest
/usr/bin/ld: ../libffdynamic.so: undefined reference to `deflateInit_'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `deflateInit2_'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `compress'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `uncompress'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `deflate'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `compress2'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `deflateEnd'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `inflateSync'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `inflate'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `inflateInit2_'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `inflateInit_'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `inflateEnd'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `deflateBound'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `inflateReset'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `deflateReset'
/usr/bin/ld: ../libffdynamic.so: undefined reference to `zlibCompileFlags'
collect2: error: ld returned 1 exit status
make[2]: *** [FFdynamic/davTests/CMakeFiles/avMixerTest.dir/build.make:107: FFdynamic/davTests/avMixerTest] Error 1
make[1]: *** [CMakeFiles/Makefile2:192: FFdynamic/davTests/CMakeFiles/avMixerTest.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Xingtao** [comment]
Ok, try add 'm' 'z' to the last line
```
target_link_libraries(ialService
  | PUBLIC ffdynamic::ffdynamic httputil::httputil pbtree::pbtree ffdynaProto::ffdynaProto protobuf::libprotobuf
  | PUBLIC lzma boost_system Threads::Threads z m)
```

I guess you compiled FFmpeg as static libraries, which cause those linking problem.
If issue remain, try compiling FFmpeg as dynamic libraries.

**Comment by Creepios** [comment]
Yes, now works. It was really because ffmpeg was installed as a static library.
