### ISSUE TITLE
how add audio output in Dynamic Detect streamlet

### ISSUE THREAD

**Issue by ghmin** [Xingtao/FFdynamic#8]
I  study this  project to edit videos, and try to write dehazor plugin and dynamic detect streamlet following the guide.
But I found that it was hard that  adding the audio into the dynamic detect streamlet ,
I saw the source code and found any audio handling logic yet.
How could I add the audio raw output with the dynamic detect streamlet example ?

**Comment by ghmin** [comment]
And I try to copy the code of  MixStreamletBuilder into the example , but it seems not work.

`auto audioMixes = streamlet->getWavesByCategory(DavWaveClassAudioMix());
    
    shared_ptr<DavWave> audioMix;
    if (audioMixes.size() > 0)
        audioMix = audioMixes[0];
    if (audioMix)
        streamlet->addOneInAudioRawEntry(audioMix);


    if (audioMix) {

        streamlet->addOneOutAudioRawEntry(audioMix);
    }`

**Comment by Xingtao** [comment]
Hi, what process pattern would you like to implement ?  

If it is somehow like the following, you could refer to this test: FFdynamic/davTests/streamletMixTest.cpp

```
input1 -> | mix N streams (both audio and video) |  -> dehaze 
input2 -> |
......
inputN ->|                                          
```

**Comment by ghmin** [comment]
thanks，I solve this already .
Copy  MixStreamletBuilder  and change the output like this：

>     if(postDraws.size()>0){
        auto postDraw =  postDraws[0];

        streamlet->addOneOutVideoRawEntry(postDraw);
        DavWave::connect(videoMix.get(), postDraw.get());
    }
    else{
        streamlet->addOneOutVideoRawEntry(videoMix);
    }
