### ISSUE TITLE
Mixer layout details

### ISSUE THREAD

**Issue by EvK** [Xingtao/FFdynamic#9]
Hi, I'm trying to mix two videos, each of which is 1920x1080, and stack them horizontally. That's just one case of several I have, so I'm trying to understand how layouts work in general. I set up a mixer with width 3840 and height 1080 (in video_mix settings in json config file), and setup output with the same (width 3840, height 1080). Then I use auto layout (also tried explicitly eHorizonal_2). It does input videos fine, however they are both heavily downscaled and put in small rectangles close to the center of resulting 3840x1080 video. What I want to achieve instead is for them to be stacked without any gaps and downscaling (first video on the left in original resolution of 1920x1080, and second video on the right, also in original resolution). I tried eLayoutSpecific but I'm not sure if it's supported yet. I also looked at code and noticed eHorizonal_2 (for example) coordinates are defined as "{{0,60},{30,30},{60,60},{60,60}}}", which is not very clear to me. Can you please help me with this issue?

**Comment by Xingtao** [comment]
hi,  layout =  eLayoutSpecific (with desire layout coordinates) is not implemented right now.
So, you have to change the code, and rebuild
```
Change {{0,60},{30,30},{60,60},{60,60}}} to  {{0,60},{0,0},{60,60},{120,120}}} should work.
```

{{0,60},{30,30},{60,60},{60,60}}}  is two cell's up left point coordinate and width, heigh,  in a 120x120 
canvas, namely:
cell1's up left point (0, 30), width and height (60, 60) 
cell2's up left point (60, 30), width and height (60, 60) 

To avoid gap between two cells,  set  'margin = 0' inside VideoMixSetting of 'ialConfig.json' file.

**Comment by EvK** [comment]
Thanks, did that and it's working. If you don't mind, I have couple of questions more:
1. Is it easy enough (for myself) to implement basic specific layout? All I need is being able to pass those `{{0,60},{0,0},{60,60},{120,120}}` from client calling the api, and complications like overlap and such do not matter for me. So basically I want client to be able to pass cell configuration in relative (0-120) coordinates.
2. Is it possible to remove one participant video, while leaving audio only? Basically make one participant's cell width and height zero. Because if I remove it completely, then audio is also removed.
3. Is it possible to define mixer dimensions dynamically? For example, I can have output configurations of multiple sizes, and can choose one to use, but mixer dimensions seem to be hardcoded. It seems the only way to have different mixer dimensions is to start separate processes with separate configurations.
4. What's the purpose of "create room" api? You provide unique id when creating the room, but it seems the room is global, that is - only one room can exist. No apis accept a room id or something. For example, "add stream" api just adds stream to that one global room.

Thanks for your work, really nice application.

**Comment by Xingtao** [comment]
> Thanks, did that and it's working. If you don't mind, I have couple of questions more:
> 
> 1. Is it easy enough (for myself) to implement basic specific layout? All I need is being able to pass those `{{0,60},{0,0},{60,60},{120,120}}` from client calling the api, and complications like overlap and such do not matter for me. So basically I want client to be able to pass cell configuration in relative (0-120) coordinates.

Yes, describe each cell in (0-120) coordinates. 
And it may take some work.
You need add process code in cellMixer.cpp's CellMixer::onUpdateLayoutEvent  to make the new specific layout done.

> 2. Is it possible to remove one participant video, while leaving audio only? Basically make one participant's cell width and height zero. Because if I remove it completely, then audio is also removed.

Yeah, your idea will work. Just passing all 0s as this participant's cell coordinate and do according process in cellMixer.cpp (namely, skip copy this cell when all  0s).
Moreover, if specific layout is implemented,  this feature could be got for free. 


> 3. Is it possible to define mixer dimensions dynamically? For example, I can have output configurations of multiple sizes, and can choose one to use, but mixer dimensions seem to be hardcoded. It seems the only way to have different mixer dimensions is to start separate processes with separate configurations.

This may take some effort. The current implementation in 'ialService.cpp', only instantiate one mixer. And all dynamic changes assuming only one mixer there.
So, to use several mixer in one task, apis and message formats have to be modified.


> 4. What's the purpose of "create room" api? You provide unique id when creating the room, but it seems the room is global, that is - only one room can exist. No apis accept a room id or something. For example, "add stream" api just adds stream to that one global room.

The ial application is designed working in cluster mode. So, each ial application is created by a manager process, which needs holding info of each task (use RoomId as the unique id). APIs like layout change is passing to manager process first(with roomid) and manager process relay it to proper ial process then(no need roomid anymore).  Just ignore it in your case.


> Thanks for your work, really nice application.
Glad to help and pull request is welcome.
